### PR TITLE
Simplify travis configuration

### PR DESCRIPTION
**Pull request by harrysarson**
Hi, I noticed #7 and thought I could lend a hand :)

I have added a description/rational to the three commits I have made.

### CODE REVIEW

**Comment by harrysarson** [comment]
I was wrong about the need to add the rustfmt component so I reverted that change.

Additionally, is there a reason that travis only strips the binary on mac?

**Comment by zwilias** [comment]
Primary reason for the caching strategy is this: https://levans.fr/rust_travis_cache.html

Long story short - `cache: cargo` overcaches, quite badly, and can over time lead to hugely inflated caches and a net loss in performance.

Good to know about `sudo: false`! I should've checked :D 

So `strip` - it's kind of silly. I was looking at my travis setup for `elm-instrument` (binary used as to instrument Elm code for code coverage) and noticed I only `strip` on OS X.... and blindly assumed I must've had a reason for that 😅 

Now that I'm thinking about it some more, I can't actually think of a reason, so it's probably just me being silly. So, what I'm going to do is set up a bunch of linux VM's and check a few options:
- does `strip` create a smaller binary? does it still work?
- how about `RUSTFLAGS="-C link-arg=-s"`? does this work on OSX? Does it work on Linux? Does it produce smaller binaries, and do they still work?

-> Once I've tested a few combinations, I'll see what we end up with! 😄

**Comment by zwilias** [comment]
Preliminary results:
- `RUSTFLAGS="-C link-arg=-s"` produces marginally smaller binaries on OSX vs stripping them afterwards
- the binaries still work
- this can be added to the build command pretty easily, so that's nice

I think I'll push the change, and make sure to check the Linux binary before making the next release public!

**Comment by harrysarson** [comment]
Looks good!

For what it is worth, here are the results of running strip on my linux environment:

```sh   
$ stat elm-json                                                                         
  File: 'elm-json'                                                                      
  Size: 8863639         Blocks: 17312      IO Block: 4096   regular file                
Device: ch/12d  Inode: 23925373020759279  Links: 1                                      
Access: (0777/-rwxrwxrwx)  Uid: ( 1000/   harry)   Gid: ( 1000/ hsarson)                
Access: 2019-04-25 17:22:24.299789100 +0100                                             
Modify: 2019-04-23 12:34:57.000000000 +0100                                             
Change: 2019-04-25 17:22:24.395533500 +0100                                             
 Birth: -                                                                                                      
$ strip elm-json                                                                                                     
$ stat elm-json                                                                         
  File: 'elm-json'                                                                      
  Size: 6870400         Blocks: 13424      IO Block: 4096   regular file                
Device: ch/12d  Inode: 2533274791364585  Links: 1                                       
Access: (0777/-rwxrwxrwx)  Uid: ( 1000/   harry)   Gid: ( 1000/ hsarson)                
Access: 2019-04-25 17:22:40.552689900 +0100                                             
Modify: 2019-04-25 17:22:40.589591200 +0100                                             
Change: 2019-04-25 17:22:40.595574000 +0100                                             
 Birth: -                                    
```

**Pull request merged**
